### ISSUE TITLE
dead end

### ISSUE THREAD

**Issue by mklcp** [hundredrabbits/Oquonie#16]
Although it's in the style of the game to not say a word about how to make it through, I'm blocked on a pretty weird situation:  
in the "library" level, collecting the last bird made me trapped in the room where it was hidden:  
![](https://i.imgur.com/2ulCsym.png)
Is this normal, and so there is still a mean to go out that I have to find; or is it really a problem in the game mechanic?

**Comment by Rezmason** [comment]
Ooh yes, this looks like an unintentional bug. Thanks for reporting it! I've reproduced it, and have a fix in mind. I'll submit it as a pull request for @neauoire to review. (I'll just replace the Gate in Room 146 with a standard Door, sound good? 😀 And I'll search for all rooms with only one Gate and a Wizard/Shark, and do the same thing)

The good news, @melopee, is if you quit and reopen the game, it will restore your game state to the last time you conferred with our friend the Owl. The bad news is, we can't be sure how long ago that was.

So! If you would like, I can give you some commands to enter into the game, that will get you back to this state with all your progress intact.

**Comment by Rezmason** [comment]
Nastazie rooms [144, 145 and 146](https://gist.github.com/Rezmason/e082c03c893e1f751cc6788068893291) have no doors, one gate and one wizard. I'll turn all their Gates into Doors.

**Comment by mklcp** [comment]
The bird room of the library is problematic, but I've only found the rabbit room of the library to be problematic too (when entering as bird, and becoming a rabbit).
As for getting out, I had found the cheatcodes; it was so just a matter of collecting tokens to transform oneself again (which is the main thing of the game anyway).
Thanks for the quick answer! I will close now.

**Comment by neauoire** [comment]
Thanks @Rezmason, sorry @melopee I was away for a little while :)
This has been pushed through itch 👍
